idf_component_register( SRCS 
                             "max30102_algorithm.c" 
                             "max30102_read.c" 
                             "max30102.c" 
                             "i2c_u.c" 
                             "spl06_001.c" 
                             "dht11.c" 
                             "main.c"
                        INCLUDE_DIRS ".")
